# Tarea 01 - Numpy

**Profesor: Ignacio Araya**

**Curso: Programación II**

In [15]:
import numpy as np

<h3> Completa los siguientes ejercicios. Documente su código según sea necesario. 10 puntos cada ejercicio</h3>
<br>

<ol>
<li><font size=3> Cree un Numpy Array de 5 por 7 de números enteros aleatorios con valores entre 3 y 11 inclusive. Luego haz lo siguiente:
     <ol> <li>Verifique el tipo de datos del array</li>
         <li>Encuentre el máximo de todo el array</li>
         <li>Encuentre el valor mínimo de cada fila</li>
         <li>Encuentre el índice donde ocurre el valor mínimo de cada fila</li>
     </ol></font></li>
</ol>

In [16]:
x = random.randint(3, 12, size=(5, 7))
x

array([[ 4,  4,  4,  7,  4, 10, 11],
       [ 6,  7,  7,  6, 10,  7, 10],
       [ 7,  3,  7,  7,  5,  7, 10],
       [ 8, 10,  4,  8, 10, 11,  3],
       [ 4, 11,  9,  4, 11,  7, 10]])

In [17]:
tipo = x.dtype
tipo

dtype('int32')

In [19]:
max = np.max(x)
max

11

In [21]:
min = np.min(x, axis=1)
min

array([4, 6, 3, 3, 4])

In [23]:
ind = np.argmin(x, axis=1)
ind

array([0, 0, 1, 6, 0], dtype=int64)

<ol start='2'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array: </font></li>

```python
#Resultado
array([ 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99])
```
</ol>

In [3]:
a = array([ 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99])
a

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [4]:
b = array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
b

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Cree un numpy array de 4 por 2 por 3 con valores normalmente distribuido</font></li>
   
</ol>

In [6]:
c = random.normal(loc=0.0, scale=1.0, size=(4, 2, 3))
c

array([[[ 0.49864099,  0.46411924, -0.2178669 ],
        [-1.03901729, -2.46476857,  0.35584624]],

       [[-1.90638809,  0.50891471, -1.05187591],
        [-1.05601931, -1.12836342, -0.38941066]],

       [[-0.40457821, -0.60358035, -0.43305759],
        [-0.28519101, -1.95183417, -0.88377046]],

       [[ 0.07212879, -1.18033203,  0.83686525],
        [ 1.09549819, -0.83882774, -0.07283085]]])

<ol start='5'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array (incluyendo el tipo correcto de datos): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [28]:
d = array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])
tipo = d.dtype
print(d, tipo)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]] int32


<ol start='6'>
   
<li> <font size='3'>Dado el numpy array </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Ingrese el código que selccione sólo los últimos 4 elementos:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Ingrese el código que selecciones el siguiente subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [29]:
e = array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
e

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [30]:
e1 = e[-4:]
e1

array([27, 29, 31, 33])

In [32]:
e2 = e[::3]
e2

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Dado el numpy array en 2D </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Ingrese el código que seleccione el elemento 71 en la última fila</li>
    <br>
   <li> Ingrese el código que seleccione el siguiente subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Ingrese el código que seleccione el siguiente subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [33]:
f = np.array([[69, 75, 52, 33,  7, 62, 22],
             [87, 51, 13, 75, 78, 46, 53],
             [43, 24, 58, 76,  3,  3, 57],
             [84, 86, 75, 26, 71, 77,  7],
             [75, 17, 17, 38, 54, 72, 78]])
f

array([[69, 75, 52, 33,  7, 62, 22],
       [87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7],
       [75, 17, 17, 38, 54, 72, 78]])

In [39]:
f1 = f[-2, 4]
f1

71

In [37]:
f2 = f[-3:, 3:5]
f2

array([[76,  3],
       [26, 71],
       [38, 54]])

In [38]:
f3 = f[1:4, :]
f3

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Dado el numpy array</font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Ingrese el código que seleccione todos los elementos más grandes que 7 y menores que 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Ingrese el código que selecciona todos los enteros pares más grandes que 11 y menores que 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [40]:
arr=np.arange(1,50,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [42]:
g = arr[(arr > 7) & (arr < 43)]
g

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [43]:
g1 = arr[(arr > 11) & (arr < 45) & (arr % 2 == 0)]
g1

array([16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Cree un 1D array uniformemente distribuido con 20 elementos y calcule: </font></li>


<ol>
    <li> Media</li>

   <li>Deviación estándar</li>
   
   <li>Mediana</li>
   
   <li>Media de sus valores en log</li>
</ol>
</ol>

In [44]:
h = np.random.uniform(0, 100, size=20)
h

array([16.70064358, 64.09872403, 31.09488015, 95.6899049 , 63.76795805,
       44.65910548, 98.61294946, 41.27132859, 14.77551708, 43.201974  ,
       96.77861812, 33.36812318,  3.85197484, 75.39278451,  9.53976565,
       37.2533409 , 36.59077073, 48.85072593, 83.3001862 ,  4.43777322])

In [45]:
media = np.mean(h)
media

47.16185243065753

In [46]:
DE = np.std(h)
DE

29.95054711715227

In [47]:
mediana = np.median(h)
mediana

42.23665129615198

In [48]:
media_log = np.mean(np.log(h))
media_log

3.5362134566790173

<ol start='10'>
   
<li> <font size='3'>Escriba una función que:</font></li>
    <ol>
    <br>
   <li> Tome un numpy array en 1D como input e imprima el arreglo invertido con elementos tipo flotantes</li>

For ejemplo, si ingresas el siguiente array en tu función
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
deberías imprimir

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> Tome un numpy array en 2D como input e imprima una copia del input array <b> flattened</b> a una dimensión </li>

For ejemplo, si el input array es:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
el output de tu función debería ser
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [49]:
def invertir(x):
    inv = np.flip(x).astype(float)
    print(inv)

def aplanar(x):
    plan = x.flatten()
    print(plan)

In [57]:
_1d = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23])

invertir(_1d)

[23. 21. 19. 17. 15. 13. 11.  9.  7.  5.  3.  1.]


In [58]:
_2d = np.array([[7, 4, 8, 3], [6, 3, 4, 3], [4, 7, 5, 4]])

aplanar(_2d)

[7 4 8 3 6 3 4 3 4 7 5 4]
