# Soluciones Tarea 02 - Numpy

**Profesor: Ignacio Araya**

**Curso: Programación II**

<h3> Completa los siguientes ejercicios. Documente su código según sea necesario. 10 puntos cada ejercicio</h3>
<br>

<ol>
<li><font size=3> Cree un Numpy Array de 5 por 7 de números enteros aleatorios con valores entre 3 y 11 inclusive. Luego haz lo siguiente:
     <ol> <li>Verifique el tipo de datos del array</li>
         <li>Encuentre el máximo de todo el array</li>
         <li>Encuentre el valor mínimo de cada fila</li>
         <li>Encuentre el índice donde ocurre el valor mínimo de cada fila</li>
     </ol></font></li>
</ol>

### Respuestas Item 1

In [1]:
import numpy as np

array = np.random.randint(low=3, high=12, size=(5,7))
array


array([[10, 11,  9,  4,  4,  7, 11],
       [ 5,  9,  5, 10,  5, 11,  5],
       [ 6,  7,  6,  9,  9,  4, 11],
       [ 6,  7, 10, 10,  5,  8, 11],
       [ 8, 11, 11,  7,  7,  4,  8]])

### 1.- Verificar el tipo de datos del array:


In [2]:
array.dtype


dtype('int64')

### 2.- Encontrar el máximo de todo el array:


In [3]:
np.max(array)

11

### 3.- Encontrar el valor mínimo de cada fila:


In [4]:
np.min(array, axis=1)



array([4, 5, 4, 5, 4])

### 4.- Encontrar el índice donde ocurre el valor mínimo de cada fila:

In [5]:
np.argmin(array, axis=1)

array([3, 0, 5, 4, 5])

<ol start='2'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array: </font></li>

```python
#Resultado
array([ 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99])
```
</ol>

In [6]:
array = np.arange(20) * 5 + 4
array

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [7]:
array = np.arange(4, 100, 5).reshape(4, 5)
array


array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Cree un numpy array de 4 por 2 por 3 con valores normalmente distribuido</font></li>
   
</ol>

In [8]:
array = np.random.normal(size=(4, 2, 3))
array

array([[[ 1.70046345,  1.70440632,  0.42619988],
        [ 0.26985287, -0.5082341 ,  1.26703367]],

       [[-1.02440999, -0.63986885,  0.45811018],
        [-0.18633119, -1.01576287,  0.72225408]],

       [[ 1.94740803, -2.23707666,  0.68612733],
        [-0.74430561,  0.30124701, -0.22389822]],

       [[-0.61043895,  0.71656985,  0.26245195],
        [-0.64238213, -0.24052462, -2.34576257]]])

<ol start='5'>
   
<li> <font size='3'>Ingrese el código a continuación que genera el siguiente numpy array (incluyendo el tipo correcto de datos): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [9]:
array = np.eye(6, 6, k=-2, dtype=int)
array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

<ol start='6'>
   
<li> <font size='3'>Dado el numpy array </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Ingrese el código que selccione sólo los últimos 4 elementos:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Ingrese el código que selecciones el siguiente subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

### Respuestas Item 6
### 1.-

In [10]:
array = np.array([3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
ultimas_cuatro = array[-4:]
ultimas_cuatro

array([27, 29, 31, 33])

### 2.-

In [11]:
sub_arr = array[::3]
sub_arr

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Dado el numpy array en 2D </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Ingrese el código que seleccione el elemento 71 en la última fila</li>
    <br>
   <li> Ingrese el código que seleccione el siguiente subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Ingrese el código que seleccione el siguiente subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

### Respuestas Item 7

### 1.-

In [12]:
array_2d = np.array([[69, 75, 52, 33,  7, 62, 22],
                   [87, 51, 13, 75, 78, 46, 53],
                   [43, 24, 58, 76,  3,  3, 57],
                   [84, 86, 75, 26, 71, 77,  7],
                   [75, 17, 17, 38, 54, 72, 78]])

elemento_selecionado = array_2d[4, 5]
elemento_selecionado

72

### 2.-

In [13]:
subarr = array_2d[2:5, 3:5]
subarr

array([[76,  3],
       [26, 71],
       [38, 54]])

### 3.-

In [14]:
subarr3 = array_2d[1:-1, :]
subarr3


array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Dado el numpy array</font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Ingrese el código que seleccione todos los elementos más grandes que 7 y menores que 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Ingrese el código que selecciona todos los enteros pares más grandes que 11 y menores que 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

### Respuestas Item 8
### 1.-

In [15]:
array=np.arange(1,50,3)

array[(array > 7) & (array < 43)]


array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])


### 2.-

In [16]:

array[(array > 11) & (array < 45) & (array % 2 == 0)]


array([16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Cree un 1D array uniformemente distribuido con 20 elementos y calcule: </font></li>


<ol>
    <li> Media</li>

   <li>Deviación estándar</li>
   
   <li>Mediana</li>
   
   <li>Media de sus valores en log</li>
</ol>
</ol>

### Respuestas Item 9

In [17]:
array = np.random.uniform(size=20)
print('Array creado: ', array)
# Media
mean = np.mean(array)

# Desviación estándar
std_dev = np.std(array)

# Mediana
median = np.median(array)

# Media de los valores en log
log_mean = np.mean(np.log(array))

# Imprimir resultados
print(f'\nResultados\n\nMedia: {mean}\nDesviación estándar: {std_dev}\nMediana: {median}\nMedia de los valores en log: {log_mean}')


Array creado:  [0.14474013 0.84696859 0.83201251 0.48425079 0.91619998 0.33066146
 0.78340283 0.67835387 0.69204915 0.80420907 0.26358102 0.28820031
 0.60644864 0.73935373 0.20886545 0.27144841 0.00635282 0.99327066
 0.15539089 0.4910983 ]

Resultados

Media: 0.526842930005585
Desviación estándar: 0.2914039653513263
Mediana: 0.548773471699157
Media de los valores en log: -0.965426187283484


<ol start='10'>
   
<li> <font size='3'>Escriba una función que:</font></li>
    <ol>
    <br>
   <li> Tome un numpy array en 1D como input e imprima el arreglo invertido con elementos tipo flotantes</li>

For ejemplo, si ingresas el siguiente array en tu función
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
deberías imprimir

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> Tome un numpy array en 2D como input e imprima una copia del input array <b> flattened</b> a una dimensión </li>

For ejemplo, si el input array es:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
el output de tu función debería ser
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

### Respuestas Item 10

In [18]:
# Función

def operaciones(array):
    '''
    Esta función recibe un array de numpy y retorna el array invertido si es 1D o el array aplanado si es 2D
    '''
    if array.ndim == 1:
        arr_decimal = array.astype(float)[::-1]
        print(arr_decimal)
    elif array.ndim == 2:
        arr_aplanado = array.flatten()
        print(list(arr_aplanado))
    else:
        print("Error: el input debe ser un array de 1D o 2D")


In [19]:
array = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23])
operaciones(array)

[23. 21. 19. 17. 15. 13. 11.  9.  7.  5.  3.  1.]


In [21]:
array = np.array([[7, 4, 8, 3],
                [6, 3, 4, 3],
                [4, 7, 5, 4]])
operaciones(array)


[7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4]
