# Ejercicios - NumPy

**Profesor: Ignacio Araya**

**Curso: Programación II**

### 1.

Importe numpy con el alias `np`.

In [1]:
import numpy as np

### 2.

Cree las siguientes matrices (arrays):

1. Crea una matriz de 5 ceros.
2. Crea una matriz de 10 unos.
3. Cree una matriz de 5 3,141.
4. Cree una matriz de números enteros del 1 al 20.
5. Cree una matriz de unos de 5 x 5 con un tipo d `int`.

In [2]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [3]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
c = np.array([3.141]*5)
print(c)

[3.141 3.141 3.141 3.141 3.141]


In [5]:
d = np.arange(1, 21)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
x = np.arange(0, 5)
e = np.zeros((len(x), 5))
print(e)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
y=np.array([1]*25).reshape(5,5)
x=np.ones((5,5),dtype=int)
print(y)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

Utilice Numpy para:
1. Cree una matriz 3D de 3 x 3 x 3 llena de números aleatorios extraídos de una distribución normal estándar (pista: `np.random.randn()`)
2. Transforme la matriz anterior en la forma (27,)

In [8]:
f = np.random.randn(3,3,3)
print(f)

[[[ 0.23908054  0.00557205  1.93714308]
  [ 1.8130673  -1.6694133   0.71034072]
  [-1.79509864  0.03716058 -1.48786808]]

 [[-0.84439021  0.0211388   0.25921378]
  [-0.49243402 -0.39525195 -0.61241384]
  [ 1.33166553  1.05260935  0.08998708]]

 [[ 0.4996305  -0.67348597  0.22878474]
  [-3.35353046 -0.45030395  0.02688383]
  [ 0.07689465  0.71317013 -0.13739107]]]


In [9]:
g = f.reshape(27,)
print(g)

[ 0.23908054  0.00557205  1.93714308  1.8130673  -1.6694133   0.71034072
 -1.79509864  0.03716058 -1.48786808 -0.84439021  0.0211388   0.25921378
 -0.49243402 -0.39525195 -0.61241384  1.33166553  1.05260935  0.08998708
  0.4996305  -0.67348597  0.22878474 -3.35353046 -0.45030395  0.02688383
  0.07689465  0.71317013 -0.13739107]


### 4.

Crea una matriz de 20 números espaciados linealmente entre 1 y 10.

In [10]:
h = np.linspace(1,10,20)
print(h)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Ejecute el siguiente código para crear una matriz de forma 4 x 4 y luego use la indexación para producir los resultados que se muestran a continuación.

In [11]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


```python
20
```

In [12]:
print(a[3,4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [13]:
print(a[1:,3:])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [14]:
print(a[1])

[ 6  7  8  9 10]


```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [15]:
print(a[2:4])

[[11 12 13 14 15]
 [16 17 18 19 20]]


```python
array([[ 8,  9],
       [13, 14]])
```

In [16]:
print(a[1:3,2:4])

[[ 8  9]
 [13 14]]


### 6.

Calcula la suma de todos los números en "a".

In [17]:
x=np.sum(a)
print(x)

325


### 7.

Calcula la suma de cada fila en `a`.

In [18]:
x=np.sum(a, axis=1)
print(x)

[ 15  40  65  90 115]


### 8.

Extraiga todos los valores de "a" mayores que la media de "a" (pista: utilice una máscara booleana).

In [19]:
x=np.mean(a)
print(f"media = {x}")
o=[a>x]      
print(o)

media = 13.0
[array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])]


### 9.

Encuentre la ubicación del valor mínimo en la siguiente matriz `b`:

In [20]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [21]:
x=np.argmin(b)
print(x)

6


### 10.

Encuentre la ubicación del valor máximo en la siguiente matriz 2D `c` (pista: hay muchas maneras de hacer esta pregunta, pero una búsqueda rápida en stackoverflow.com generalmente lo ayudará a encontrar la solución óptima para un problema, por ejemplo consulte [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [22]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [23]:
x = np.unravel_index(c.argmax(), c.shape)
print(x)

(2, 1)


In [24]:
x = np.argwhere(c.max==c)
print(x)

[]
